# Generated by Django 5.2.8 on 2025-12-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ad_user_profile',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='ad_user',
        ),
    ]
